Bump CUDSS to v0.2
MadNLP/MadNLP.jl pull request #338
Opened 2024-05-14 16:28 UTC by michel2323

2024-05-30 00:11 UTC, amontoison commented
The errors are related to this issue: https://github.com/exanauts/CUDSS.jl/issues/45.
I will send an email to the CUDSS team with a MWE.

2024-07-04 03:41 UTC, amontoison commented
The issue is fixed with CUDSS.jl v0.3.0.

2024-07-04 03:42 UTC, amontoison requested changes

2024-07-04 03:42 UTC, amontoison commented on lib/MadNLPGPU/Project.toml
> +CUDSS = "0.1, 0.2"
```suggestion
CUDSS = "0.3"
```

2024-07-15 15:41 UTC, frapac commented
Superseded by #355

2024-07-15 15:41 UTC, closed without merging